version: "3.8"
services:
  backend:
    container_name: blp-backend-app
    hostname: blp-backend-app
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - 4444:4444
    depends_on:
      postgresdb:
        condition: service_healthy
    networks:
      - blp-backend
  postgresdb:
    container_name: blp-backend-db
    image: postgres:13
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 3s
      retries: 5
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - blp-backend

volumes:
  pgdata:
networks:
  blp-backend:
